### ISSUE TITLE
Send natification on flash.events.Event.DEACTIVATE (Android)

### ISSUE THREAD

**Issue by DenisSokoloff** [myflashlab/GCM-ANE#20]
I try to send natification on our server when player DEACTIVATE Android App 
Server don't get request. Request stops in progress

Request continues when I ACTIVATE app (But I need before).

I need finish request on DEACTIVATE, how I can to make this?
http://prntscr.com/bbw69c

It works on iOS, but Android stops it.

**Comment by Gamezhero** [comment]
added
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>

and use on DEACTIVATE 
NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;

When request is done 
NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL;

**Comment by myflashlab** [comment]
> I try to send natification on our server when player DEACTIVATE Android App 

I'm not sure I understood the question. GCM notifications are coming from server. how can they know when the app is about to be closed?

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
