### ISSUE TITLE
How I can remove red circle natification on icon of app on iOS?

### ISSUE THREAD

**Issue by DenisSokoloff** [myflashlab/GCM-ANE#21]
How I can remove red natification on icon of app on iOS?

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
