### ISSUE TITLE
How do I set the sound for the notification to Default instead of customise my own

### ISSUE THREAD

**Issue by menicon** [myflashlab/GCM-ANE#22]
Hi, How do I set the sound for the notification to Default (User's SMS ringtone) instead of customise my own

**Comment by myflashlab** [comment]
simply not setting the sound will play the default sound instead.

**Comment by menicon** [comment]
Hi, not setting it, it will not play anysound.

**Comment by myflashlab** [comment]
have you tried sending an empty string? ```""```

**Comment by menicon** [comment]
Yes I did tried.

**Comment by myflashlab** [comment]
I'll have a closer look and let you know.

**Comment by menicon** [comment]
I realise, I did not turn on my Media Volume, once I unmute my Media volume it works, but my whatsapp & facebook still have notification sound, even my Media Volume is mute.

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
