### ISSUE TITLE
App crashes when setSmallIcon to my png

### ISSUE THREAD

**Issue by menicon** [myflashlab/GCM-ANE#23]
Hi,

The "setLargeIconSDcard" is working and displayed my icon properly, but when I try to setSmallIcon:
{"params":["MyIcon.png"],"name":"setSmallIcon"}.

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
