### ISSUE TITLE
App crush if i 've got push message

### ISSUE THREAD

**Issue by newrachael** [myflashlab/GCM-ANE#26]
hi, I want to use your product for my air mobile application.
but have some problems.

I send a message from server(push message), onMessage is called correctly
but 
1. Debug build 
2. there is no message(no notification) on device status bar 
3. Run build
4. if I send a message from server, application has been crushed.

Flash builder,Flex sdk 4.6.0, air sdk 3.4

---
- Android 4.4 or higher , need "android-support-v4.jar", but androidSupport.ane dose not include. is it related my problem?

thans you.

**Comment by myflashlab** [comment]
Here are some tips:

1. you should notice that when on FlashBuilder IDE, the debug and release modes are changing the application package name which may cause the problem when dealing with GCM ANE

2. familiarize yourself with how the [preventDefault](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/gcm/Gcm.html#preventDefault) method works.

3. Always use the latest AIR SDK! You are using AIR SDK 3.4! WOW, that's tooooo old!

4. And finally, make sure you are watching the video screencasts about [how to embed ANEs into your projects](https://www.youtube.com/watch?v=Z7K3QDUUEf0&index=2&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O). You may find some helpful notes there.

**Comment by myflashlab** [comment]
Please let us know how it goes. Thanks.

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
