### ISSUE TITLE
GCM crash when resume app

### ISSUE THREAD

**Issue by XeerSoft** [myflashlab/GCM-ANE#27]
Hi, found one issue from GCM, on IOS. When app resume by close a popup external window(Browser) the app crash, error message as below:

ReferenceError: Error #1069: Property aps not found on String and there is no default value.
    at com.myflashlab.air.extensions.gcm.ios::Ios/onInvokeGcm()
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at flash.desktop::NativeApplication/dispatchEvent()
    at com.distriqt.extension.core::Core/extension_statusHandler()

Device using:
Ipad mini 4
IOS 9.3.5
Starling + feather
AIR 22
MyFlashLab GCM ANE version:  5.0.0

Can please help advice, what should I do?

Thank you

**Comment by myflashlab** [comment]
would you please try running the ane without using other ANE providers? do this first to make sure there is no conflict between ANEs...

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
