### ISSUE TITLE
App crashes on receiving GCM

### ISSUE THREAD

**Issue by chetan1997** [myflashlab/GCM-ANE#28]
I am a club member since November 2015 - have been happily using a few of the ANE's in my Android mobile app.

I have the most recent myflashlabs-Package-26 and the recent dependency libs.
My dev-env: FB-4.6, ApacheFlex-4.15 + AIR-21.0, Android Device-Moto G (5.1).

When the app receives the GCM, most of the times the app crashes.  Long press on mobile menu button shows my app in the app list.  Tapping on my app brings it to the foreground - and starts the app afresh.

I have removed all other ANE's from the code as well as the build process.  Still the problem remains.

I hadn't faced any of these issues when I was using myflashlabs-Package-4 - for 3 to 4 months.

I have attached the code for: (1) manifest file (2) Actionscript (3) PHP.  All these are pretty much copies of your samples and examples from github.

Gcm.isSandbox = false;
gcm.preventDefault = false;

Please let me know what else I should be doing.  Should I be calling some other myflashlabs ANE init function?

Thanks.
Chetan.
[GCM Myflashlabs Query.txt](https://github.com/myflashlab/GCM-ANE/files/461052/GCM.Myflashlabs.Query.txt)

**Comment by redsparrowWang** [comment]
info http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/gcm/Gcm.html
Gcm.isSandbox is for iOS

**Comment by myflashlab** [comment]
From the attached .txt file I couldn't confirm if you have corrected the dependency ANEs or not. please check the changelog [here](https://github.com/myflashlab/GCM-ANE#changelog) and confirm if you have updated your dependency ANEs? 

If yes, please send us the Logcat messages so we can study this further.

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
