### ISSUE TITLE
RegisterationIdReceived but always getting MismatchSenderId 

### ISSUE THREAD

**Issue by tfnsyl** [myflashlab/GCM-ANE#29]
Hi, I have been testing your sample code. I followed this steps:
- copied project and replaced ANE with club version,
- changed project name and manifest as described.
- created new Project on Google Developer Console,
- copied senderID in Project Settings page and changed ANDROID_SENDERID with that, 
- received registrationID and copied it to [test page](http://www.myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/demoV4/)
- copied Server API Key from Credentials Page and tested on test page.

When I test it, I always get MismatchSenderId. 

Also I set GCM.isSandBox to both true and false, and still no luck.

What am I missing?

**Comment by myflashlab** [comment]
Receiving ```MismatchSenderId``` means that your Server API key or Sender ID or the generated RegID are not matching. You should make sure you are setting everything correctly according to the sample files? pay double attention to how the manifest settings are set. and change the setting based on your own information and also change the package name (for Android) and the bundle id (for the iOS side) according to your own application package name. Moreover, you may find some tips if you search for the problem on stackoverflow. for example this one: http://stackoverflow.com/questions/11313342/why-do-i-get-mismatchsenderid-from-gcm-server-side

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
