### ISSUE TITLE
GCM V4.0 Google reply: Unauthorized Error 401

### ISSUE THREAD

**Issue by flashomer** [myflashlab/GCM-ANE#31]
Hi, I made all my settings but I get an error like this on the web side. 
"Google reply: Unauthorized Error 401"

Now we have FCM like to travel?
https://developers.google.com/cloud-messaging/http

FCM with key number, I get an error that I created in this way.
https://gupon.net/gcm/gcm.mp4

Can you help me?
What am I doing wrong?

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
