### ISSUE TITLE
GCM + InAppPayments

### ISSUE THREAD

**Issue by ALIENreal** [myflashlab/GCM-ANE#36]
Can't compile ios version with GCM ane and InAppPayments. Get this error:
[https://drive.google.com/file/d/0B9_KSMhHviMkQ2d0TW9vUmpnbnc/view?usp=sharing](url)
Conflict with GCM  ane and overrideAir ane on IOS, as I understand.

**Comment by myflashlab** [comment]
Dear developer(s), More than a year ago Google Deprecated GCM in favor of [FCM](https://github.com/myflashlab/Firebase-ANE). Since Google is not updating it, we didn't update it neither and have removed the product from sale. We understand that some of our customers might still be using the old GCM ANE and we'd like to help you out with the transition. Please contact us through http://www.myflashlabs.com/contact/ and ask for a discount for moving away from GCM. My colleagues should get back to you fast to let you know about how to do the transition.

Thanks,
MyFlashLabs Team
